### ISSUE TITLE
will support yolo obb to dota？

### ISSUE THREAD

**Issue by chaoer** [regainOWO/dataset_convert#1]
another questions：
in the le180yolo2dota line 60, seem to be has no conversion?

https://github.com/regainOWO/object_detection_tools/blob/f3aee7808f112d0176260f3b6dcd14d68ba84df0/convert/le180yolo2dota.py#L60C4-L60C4

**Comment by regainOWO** [comment]
@chaoer  it has conversion, i use the opencv funciton `cv2.boxPoints` this script is used on my project, maybe its not fit your dataset type.
i will update my project later!
* opencv-python >= 4.5.1

**Comment by chaoer** [comment]
thanks @regainOWO
